import Head from "next/head";
import { useRef } from "react";
import Carousel from "@/components/index_page_components/Carousel";
import SectionTitle from "@/components/index_page_components/SectionTitle";
import LatestReleasesCards from "@/components/index_page_components/LatestReleasesCards";
import PodcastCards from "@/components/index_page_components/PodcastCards";
import JTWTCards from "@/components/index_page_components/JTWTCards";
import VoDCards from "@/components/index_page_components/VoDCards";
import Banner from "@/components/index_page_components/Banner";
import YTCards from "@/components/index_page_components/YTCards";
import { motion } from "framer-motion";
import { useInView } from "framer-motion";
import { Box,Text,Flex } from "@chakra-ui/react";
export default function Home() {

  const MotionBox = ({ children }) => {
    const ref = useRef(null);
    const isInView = useInView(ref, { once: true, margin: "0px" });
  
    return (
      <motion.div
        ref={ref}
        initial={{ opacity: 0, y: 50 }}
        animate={isInView ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.6, ease: "easeOut" }}
      >
        {children}
      </motion.div>
    );
  };

  return (
    <>
      <div style={{ overflow: "hidden", paddingBottom: "10px" }}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Carousel />
        
        <MotionBox>
          <SectionTitle text={"Latest Releases"} />
          <LatestReleasesCards />
        </MotionBox>

        <MotionBox>
          <SectionTitle text={"Jyot Podcast"} />
          <PodcastCards />
        </MotionBox>

        <MotionBox>
          <Flex
            justifyContent={"center"}
            alignItems={"center"}
            w={"100vw"}
            h={"100px"}
            bg={"#de2225"}
          >
            <Text fontSize={"30px"} color={"white"} fontFamily={"Oswald, sans-serif"}>
              Enrich your soul by contributing towards Prabhavana of Jinvachan.
            </Text>
          </Flex>
        </MotionBox>

        <MotionBox>
          <SectionTitle text={"Jo Tare Wo Tirth"} />
          <JTWTCards />
        </MotionBox>

        <MotionBox>
          <SectionTitle text={"Vision of Dharmacharya"} />
          <VoDCards />
        </MotionBox>

        <br />
        <br />
        <br />

        <MotionBox>
          <Banner />
        </MotionBox>

        <MotionBox>
          <SectionTitle text={"Mahasattvashali"} />
          <YTCards />
        </MotionBox>
      </div>
    </>
  );
}
