import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/index_page_components/Navbar";
import Carousel from "@/components/index_page_components/Carousel";
import SectionTitle from "@/components/index_page_components/SectionTitle";
import LatestReleasesCards from "@/components/index_page_components/LatestReleasesCards";
import PodcastCards from "@/components/index_page_components/PodcastCards";
import JTWTCards from "@/components/index_page_components/JTWTCards";
import VoDCards from "@/components/index_page_components/VoDCards";
import Banner from "@/components/index_page_components/Banner";
import YTCards from "@/components/index_page_components/YTCards";
import Footer from "@/components/index_page_components/Footer";

import { Box,Text,Flex } from "@chakra-ui/react";
export default function Home() {
  return (
    <>
    <div style={{overflow:"hidden",paddingBottom:"10px"}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel />
      <SectionTitle text={"Latest Releases"} />
      <LatestReleasesCards />
      <SectionTitle text={"Jyot Podcast"} />
      <PodcastCards />

      <Flex justifyContent={'center'} alignItems={'center'} w={'100vw'} h={'100px'} bg={'#de2225'}>
        <Text fontSize={"30px"} color={'white'} fontFamily={'Oswald, sans-serif'}>
        Enrich your soul by contributing towards Prabhavana of Jinvachan.
        </Text>
      </Flex>

      <SectionTitle text={"Jo Tare Wo Tirth"} />
      <JTWTCards />
      <SectionTitle text={"Vision of Dharmacharya"} />
      <VoDCards />
      <br/><br/><br/>
      <Banner />
      <SectionTitle text={"Mahasattvashali"} />
<YTCards />
      
      </div>
    </>
  );
}
